In [29]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import math

In [30]:
X = np.linspace(start=-5, stop=5, num=1000)

In [31]:
r = 4

In [40]:
a = np.zeros(shape=(10,10))
print(a.shape)
for I in range (-5,5):
    for J in range (-5,5):
        ref1 = (((I)**2+(J)**2<=r**2))
        print("{} {} {}".format(I,J,ref1))
        a[I+5,J+5] = ref1


(10, 10)
-5 -5 False
-5 -4 False
-5 -3 False
-5 -2 False
-5 -1 False
-5 0 False
-5 1 False
-5 2 False
-5 3 False
-5 4 False
-4 -5 False
-4 -4 False
-4 -3 False
-4 -2 False
-4 -1 False
-4 0 True
-4 1 False
-4 2 False
-4 3 False
-4 4 False
-3 -5 False
-3 -4 False
-3 -3 False
-3 -2 True
-3 -1 True
-3 0 True
-3 1 True
-3 2 True
-3 3 False
-3 4 False
-2 -5 False
-2 -4 False
-2 -3 True
-2 -2 True
-2 -1 True
-2 0 True
-2 1 True
-2 2 True
-2 3 True
-2 4 False
-1 -5 False
-1 -4 False
-1 -3 True
-1 -2 True
-1 -1 True
-1 0 True
-1 1 True
-1 2 True
-1 3 True
-1 4 False
0 -5 False
0 -4 True
0 -3 True
0 -2 True
0 -1 True
0 0 True
0 1 True
0 2 True
0 3 True
0 4 True
1 -5 False
1 -4 False
1 -3 True
1 -2 True
1 -1 True
1 0 True
1 1 True
1 2 True
1 3 True
1 4 False
2 -5 False
2 -4 False
2 -3 True
2 -2 True
2 -1 True
2 0 True
2 1 True
2 2 True
2 3 True
2 4 False
3 -5 False
3 -4 False
3 -3 False
3 -2 True
3 -1 True
3 0 True
3 1 True
3 2 True
3 3 False
3 4 False
4 -5 False
4 -4 False
4 -3 False
4 -2 False


In [41]:
print(a)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  1.  1.  1.  1.  0.  0.]
 [ 0.  0.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  0.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 0.  0.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  0.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  1.  1.  1.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]]
